### ISSUE TITLE
[PROJECT PROPOSAL: Churn prediction model]

### ISSUE THREAD

**Issue by Srish-ty** [adithya-s-k/World-of-AI#222]
## Project Request

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | An ML model to predict churn for a telecom company |
| Github | Srish-ty                 |
| Email  |        srishtymsngutte@gmail.com                           |
| Label  | Project Request                   |

https://github.com/Srish-ty/
---

**Define You**

- [x] GSSOC Participant
- [x] Contributor

# Churn Predictor 

## Scope

It helps companies to know where in which region the churn rate is more and how likely the new customer is to leave the services.

## Timeline

[The project's estimated start and end dates, milestones, and deadlines for deliverables]

## Video Links or Support Links

[Links that can support the project in anyway]

**Comment by Srish-ty** [comment]
@miraj0507 please assign this issue to me

**Comment by Srish-ty** [comment]
@adithya-s-k , @avijit1999 , @ADITYADAS1999  , @miraj0507  ,can you please assign his issue to me adding gssoc2023 label ? And kindly review the pr

**Comment by CodeitVasu** [comment]
Please assign this issue to me under gssoc'23 label.

**Comment by Kyouma45** [comment]
I am interested in working on this issue. Please assign me this issue
